This is a basic workflow that is manually triggered
name: Lovisas workflow

Controls when the action will run. Workflow runs when manually triggered using the UI
or API.
on:
  workflow_dispatch:
     inputs: 
      show_message:
       description: "Log errors if tests fails"
       required: true
       default: "false"

A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "error_log"
  error_log:
    runs-on: ubuntu-latest

    steps:
      
uses: actions/checkout@v4
    # Test: Make an API call and check the response
name: Test API response
    run: |

          API_URL="https://opendata-download-metfcst.smhi.se/api/category/pmp3g/version/2/geotype/point/lon/17.0/lat/59.0/data.json"

          response=$(curl -s -w "%{http_code}" -o /dev/null $API_URL)

          if [ "$response" -eq 200 ]; then
            echo "API response successful: Status code 200"
          else
            echo "API request failed with status code $response"
            exit 1
          fi

      # Failing step if show_message is 'false'
      
name: Failing step if show_message is 'false'
      run: |
        echo "Error has occurd" > error.log
        exit 1
      if: ${{ github.event.inputs.show_message == 'false' }}
    # Upload error log if there is failure
name: Upload error log
    if: failure()
    uses: actions/upload-artifact@v3
    with: 
      name: error-log
      path: error.log
